# Generated by Django 4.2.30 on 2026-07-07 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationSession',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('tone', models.CharField(default='polite_conversational', max_length=32)),
                ('latency_profile', models.CharField(default='balanced', max_length=32)),
                ('provider_config', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('expired', 'Expired'), ('failed', 'Failed')], default='active', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'expires_at'], name='translation_status_334813_idx')],
            },
        ),
    ]
